docker/web/project/glue/urls.py
"""URL definitions for the glue project."""
from django.conf.urls import include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('glue_auth.urls')),
    url(r'^', include('price_monitor.urls')),
]

docker/web/project/glue_auth/urls.py
"""URL definitions for the glue_auth module."""
from django.conf.urls import url
from django.contrib.auth.views import login, logout_then_login


app_name = 'glue_auth'
urlpatterns = [
    url(r'^login/$', login, {'template_name': 'glue_auth/login.html'}, name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
]

docker/web/project/glue_auth/templates/glue_auth/base.html
<!DOCTYPE html>{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block pagetitle %}Pricemonitor Site{% endblock %}</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        {% block css_links %}{% endblock %}
        {% block css_inline %}{% endblock %}
        {% block js_links %}{% endblock %}
        {% block js_inline %}{% endblock %}
    </head>
    <body>
        {% block content %}Intentionally blank page.{% endblock %}
    </body>
</html>

docker/web/project/glue_auth/templates/glue_auth/login.html
{% extends 'glue_auth/base.html' %}


{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    <form method="post" action="{% url 'glue_auth:login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
{% endblock %}

docker/web/project/glue_auth/templates/price_monitor/angular_index_view.html
{% extends "price_monitor/angular_index_view.html" %}


{% block footer %}
<div class="row">
    <div class="col-md-12"><em>Template-Block: footer</em></div>
</div>
{% endblock %}